version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/data/grafana:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: "exchange"
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "admin"
      INFLUXDB_USER: "user"
      INFLUXDB_USER_PASSWORD: "password"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  exchange:
    build:
      context: .
      args:
        BIN_FILE_NAME: "exchange"
    environment:
      INFLUX_HOST: "influxdb"
      ZIPKIN_HOST: "zipkin"
      EXCHANGE_SERVICE_PATH: "https://api.exchangeratesapi.io"
    ports:
      - 9000:9000